#pragma once

// Minimal WireGuardNT API declarations used by EasyWG Server.
// API names and ABI structures follow the public WireGuardNT interface.

#include <winsock2.h>
#include <windows.h>
#include <ws2ipdef.h>
#include <iphlpapi.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable : 4324) // WireGuard ABI structs are intentionally 8-byte aligned.
#endif

#ifndef EASYWG_ALIGNED
#  ifdef _MSC_VER
#    define EASYWG_ALIGNED(n) __declspec(align(n))
#  else
#    define EASYWG_ALIGNED(n) __attribute__((aligned(n)))
#  endif
#endif

typedef struct _WIREGUARD_ADAPTER *WIREGUARD_ADAPTER_HANDLE;

#define WIREGUARD_KEY_LENGTH 32

typedef enum _WIREGUARD_LOGGER_LEVEL {
    WIREGUARD_LOG_INFO,
    WIREGUARD_LOG_WARN,
    WIREGUARD_LOG_ERR
} WIREGUARD_LOGGER_LEVEL;

typedef VOID(CALLBACK *WIREGUARD_LOGGER_CALLBACK)(
    WIREGUARD_LOGGER_LEVEL Level,
    DWORD64 Timestamp,
    LPCWSTR Message);

typedef enum _WIREGUARD_ADAPTER_LOG_STATE {
    WIREGUARD_ADAPTER_LOG_OFF,
    WIREGUARD_ADAPTER_LOG_ON,
    WIREGUARD_ADAPTER_LOG_ON_WITH_PREFIX
} WIREGUARD_ADAPTER_LOG_STATE;

typedef enum _WIREGUARD_ADAPTER_STATE {
    WIREGUARD_ADAPTER_STATE_DOWN,
    WIREGUARD_ADAPTER_STATE_UP
} WIREGUARD_ADAPTER_STATE;

typedef enum _WIREGUARD_ALLOWED_IP_FLAG {
    WIREGUARD_ALLOWED_IP_REMOVE = 1 << 0
} WIREGUARD_ALLOWED_IP_FLAG;

typedef struct EASYWG_ALIGNED(8) _WIREGUARD_ALLOWED_IP {
    union {
        IN_ADDR V4;
        IN6_ADDR V6;
    } Address;
    ADDRESS_FAMILY AddressFamily;
    BYTE Cidr;
    WIREGUARD_ALLOWED_IP_FLAG Flags;
} WIREGUARD_ALLOWED_IP;

typedef enum _WIREGUARD_PEER_FLAG {
    WIREGUARD_PEER_HAS_PUBLIC_KEY = 1 << 0,
    WIREGUARD_PEER_HAS_PRESHARED_KEY = 1 << 1,
    WIREGUARD_PEER_HAS_PERSISTENT_KEEPALIVE = 1 << 2,
    WIREGUARD_PEER_HAS_ENDPOINT = 1 << 3,
    WIREGUARD_PEER_REPLACE_ALLOWED_IPS = 1 << 5,
    WIREGUARD_PEER_REMOVE = 1 << 6,
    WIREGUARD_PEER_UPDATE_ONLY = 1 << 7
} WIREGUARD_PEER_FLAG;

typedef struct EASYWG_ALIGNED(8) _WIREGUARD_PEER {
    WIREGUARD_PEER_FLAG Flags;
    DWORD Reserved;
    BYTE PublicKey[WIREGUARD_KEY_LENGTH];
    BYTE PresharedKey[WIREGUARD_KEY_LENGTH];
    WORD PersistentKeepalive;
    SOCKADDR_INET Endpoint;
    DWORD64 TxBytes;
    DWORD64 RxBytes;
    DWORD64 LastHandshake;
    DWORD AllowedIPsCount;
} WIREGUARD_PEER;

typedef enum _WIREGUARD_INTERFACE_FLAG {
    WIREGUARD_INTERFACE_HAS_PUBLIC_KEY = 1 << 0,
    WIREGUARD_INTERFACE_HAS_PRIVATE_KEY = 1 << 1,
    WIREGUARD_INTERFACE_HAS_LISTEN_PORT = 1 << 2,
    WIREGUARD_INTERFACE_REPLACE_PEERS = 1 << 3
} WIREGUARD_INTERFACE_FLAG;

typedef struct EASYWG_ALIGNED(8) _WIREGUARD_INTERFACE {
    WIREGUARD_INTERFACE_FLAG Flags;
    WORD ListenPort;
    BYTE PrivateKey[WIREGUARD_KEY_LENGTH];
    BYTE PublicKey[WIREGUARD_KEY_LENGTH];
    DWORD PeersCount;
} WIREGUARD_INTERFACE;

typedef WIREGUARD_ADAPTER_HANDLE(WINAPI WIREGUARD_CREATE_ADAPTER_FUNC)(LPCWSTR, LPCWSTR, const GUID *);
typedef WIREGUARD_ADAPTER_HANDLE(WINAPI WIREGUARD_OPEN_ADAPTER_FUNC)(LPCWSTR);
typedef VOID(WINAPI WIREGUARD_CLOSE_ADAPTER_FUNC)(WIREGUARD_ADAPTER_HANDLE);
typedef VOID(WINAPI WIREGUARD_GET_ADAPTER_LUID_FUNC)(WIREGUARD_ADAPTER_HANDLE, NET_LUID *);
typedef DWORD(WINAPI WIREGUARD_GET_RUNNING_DRIVER_VERSION_FUNC)(VOID);
typedef VOID(WINAPI WIREGUARD_SET_LOGGER_FUNC)(WIREGUARD_LOGGER_CALLBACK);
typedef BOOL(WINAPI WIREGUARD_SET_ADAPTER_LOGGING_FUNC)(WIREGUARD_ADAPTER_HANDLE, WIREGUARD_ADAPTER_LOG_STATE);
typedef BOOL(WINAPI WIREGUARD_GET_ADAPTER_STATE_FUNC)(WIREGUARD_ADAPTER_HANDLE, WIREGUARD_ADAPTER_STATE *);
typedef BOOL(WINAPI WIREGUARD_SET_ADAPTER_STATE_FUNC)(WIREGUARD_ADAPTER_HANDLE, WIREGUARD_ADAPTER_STATE);
typedef BOOL(WINAPI WIREGUARD_GET_CONFIGURATION_FUNC)(WIREGUARD_ADAPTER_HANDLE, WIREGUARD_INTERFACE *, DWORD *);
typedef BOOL(WINAPI WIREGUARD_SET_CONFIGURATION_FUNC)(WIREGUARD_ADAPTER_HANDLE, const WIREGUARD_INTERFACE *, DWORD);

#ifdef _MSC_VER
#pragma warning(pop)
#endif

#ifdef __cplusplus
}
#endif
